### ISSUE TITLE
phBridge.getScene() not available in sdk 1.2.0

### ISSUE THREAD

**Issue by jeroenbeuz** [PhilipsHue/PhilipsHueSDK-Java-MultiPlatform-Android#38] opened 2017-08-10 09:32 UTC
The new sdk version 1.2.0 does not have the getScene() method, to get a scene with it's lightstates. The method is completely gone in the PHBridge class. The PHGroupClass is also gone from the SDK. What happened? Did these get relocated?

**Comment by jhvdb87** [comment] 2017-08-18 13:07
The problem is fixed in the 1.20.1 release.

**Comment by gkamperis** [comment] 2017-08-18 21:57
This was built with a different Java version target than the previous library.
Most Android development is NOT Java 8.

**Comment by danzada1** [comment] 2017-08-19 05:19
Yes I am also having trouble compiling due to Java 8. Can you please rebuild with Java 7?

**Comment by jhvdb87** [comment] 2017-08-19 09:25
I changed the compliance level back to 1.6.

**Comment by gkamperis** [comment] 2017-08-19 09:49
Works great!
Thanks

**Closed** 2017-08-20 11:27 UTC
